# Manipulación y álgebra de tensores en Tensorflow

Entregable: Un cuaderno, escrito de sus manos, repitiendo y si desean modificando el primer cuaderno

## 1. Importar librerías

In [1]:
import tensorflow as tf
import numpy as np

## 2. Esenciales

In [2]:
t0 = tf.constant(4)
print (t0)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
t1 = tf.constant([1, 3, 4])
print (t1)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)


In [4]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print (t23)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
t235 = tf.constant([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]], 
                    [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])
print (t235)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


In [6]:
t235.numpy().shape

(2, 3, 5)

In [7]:
t235.shape

TensorShape([2, 3, 5])

## 3. Algebra de tensores

In [8]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

print(a,"\n")
print(b,"\n")
print(tf.add(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.matmul(a,b),"\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [9]:
print(a+b, "\n")
print(a*b, "\n")
print(a@b, "\n")

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



## 4. Funiones de reducción

In [10]:
c = tf.constant([[4.0, 5.0],[10.0, 1.0]])

print (c,"\n")
print(tf.reduce_max(c),"\n")
print(tf.reduce_min(c),"\n")
print(tf.reduce_mean(c),"\n")
print(tf.argmax(c),"\n")
print(tf.nn.softmax(c),"\n")
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n")

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32) 

tf.Tensor(10.0, shape=(), dtype=float32) 

tf.Tensor(1.0, shape=(), dtype=float32) 

tf.Tensor(5.0, shape=(), dtype=float32) 

tf.Tensor([1 0], shape=(2,), dtype=int64) 

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

tf.Tensor([1. 1.], shape=(2,), dtype=float32) 



## 5. Tipo, forma y dimensión

In [11]:
t = tf.constant([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], 
                 [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
                 [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],])

print(t.dtype,"\n")
print(t.shape,"\n")
print(t.ndim,"\n")
print(t.shape[2],"\n")
print(tf.size(t.numpy()),"\n")

<dtype: 'int32'> 

(3, 2, 5) 

3 

5 

tf.Tensor(30, shape=(), dtype=int32) 



## 6. Indexación

### 6.1 Indexación en un solo eje

+ Los índices empiezan en cero
+ Los índices negativos cuentan hacia atrás desde el final
+ Los dos puntos (:) se utilizan para los cortes. inicio:final:salto

In [12]:
t1 = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Último: ", t1[-1].numpy())

Primero:  tf.Tensor(0, shape=(), dtype=int32)
Segundo:  tf.Tensor(1, shape=(), dtype=int32)
Último:  34


### 6.2 Extracción de parte de un tensor: slices 

In [13]:
print("Todo", t1[:].numpy())
print("Antes de la posición 4", t1[:4].numpy())
print("Desde la posición 4 hasta el final", t1[4:].numpy())
print("Desde la posición 2 hasta la anterior a la 7", t1[2:7].numpy())
print("Todos los elementos en posición par", t1[::2].numpy())
print("Invertido todo el orden", t1[::-1].numpy())

Todo [ 0  1  1  2  3  5  8 13 21 34]
Antes de la posición 4 [0 1 1 2]
Desde la posición 4 hasta el final [ 3  5  8 13 21 34]
Desde la posición 2 hasta la anterior a la 7 [1 2 3 5 8]
Todos los elementos en posición par [ 0  1  3  8 21]
Invertido todo el orden [34 21 13  8  5  3  2  1  1  0]


### 6.3 Indexación multi-eje

In [14]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print (t23.numpy())

[[1 2 3]
 [4 5 6]]


In [15]:
print("Posición 1,1 =", t23[1,1].numpy())
print("Segunda fila:", t23[1,:].numpy())
print("Segunda columna:", t23[:,1].numpy())
print("Última columna:", t23[:,-1].numpy())
print("Primer elemento de la última columna:", t23[0,-1].numpy())
print("Saltarse la primera columna: \n", t23[:,1:].numpy())

Posición 1,1 = 5
Segunda fila: [4 5 6]
Segunda columna: [2 5]
Última columna: [3 6]
Primer elemento de la última columna: 3
Saltarse la primera columna: 
 [[2 3]
 [5 6]]


In [16]:
t = tf.constant([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], 
                 [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
                 [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],])

print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [17]:
print("Extrae la primera capa\n", t[0,:,:])
print("Extrae la segunda capa\n", t[1])

Extrae la primera capa
 tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
Extrae la segunda capa
 tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]], shape=(2, 5), dtype=int32)


## 7. Manipular formas

In [18]:
x = tf.constant([[1],[2],[3]])

print(x.shape)
print(x.shape.as_list())

(3, 1)
[3, 1]


In [19]:
reshaped = tf.reshape(x,[1,3])

print(reshaped.numpy())
print(x.numpy())

[[1 2 3]]
[[1]
 [2]
 [3]]


Con tf.reshape los datos mantienen su disposición en la memoria y se crea un nuevo tensor, con la forma solicitada, apuntando a los mismos datos. TensorFlow usa un orden de memoria de "fila principal" de estilo C, donde incrementar el índice de la derecha corresponde a un solo paso en la memoria    

![tensor_before](tensor_before.png)

Tensor antes de reshape                            
![tensor_after](tensor_after.png).  

Tensores despues de reshape
![tensor_after2](tensor_after2.png).


### 7.1 Aplana un tensor

Operación que permite ver el orden como están organizados en memoria

In [20]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1])
print("\n t aplanado: \n", flat.numpy())

t actual: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

 t aplanado: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


Normalmente, el único uso razonable de tf.reshape es combinar o dividir ejes adyacentes (o agregar / eliminar 1s).

Para el tensor de 2x3x5, remodelar a (2x3)x5 o 2x(3x5) son dos cosas razonables, ya que los cortes no se mezclan:

In [21]:
print(t.shape.as_list())

[3, 2, 5]


In [22]:
print(tf.reshape(t, [2*3,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [23]:
print(tf.reshape(t, [2,3*5]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


No es necesario definir todos tamaños en todas las dimensiones. veámos como rehacer los dos ejemplos ateriores, respecitivamente. El -1 le dice a tf que decida cuál es la dimensión correcta

In [24]:
print(tf.reshape(t, [-1,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [25]:
print(tf.reshape(t, [3,-1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


Aunque es posible hacer el siguiente reshape no tiene sentido, porque se pierde la integridad de la información.

Asegúrese que entiende la razón

In [26]:
print(tf.reshape(t, [3,2,5]))

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### 7.2 Definición Conversión de tipos. Cast

In [27]:
f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor, dtype = tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


## 8. Radiofusión (broadcasting)

La radiodifusión es un concepto tomado de la función equivalente en numpy. En resumen, bajo ciertas condiciones, los tensores más pequeños se "estiran" automáticamente para adaptarse a tensores más grandes cuando se ejecutan operaciones combinadas en ellos.

El caso más simple y común es cuando intenta multiplicar o agregar un tensor a un escalar. En ese caso, el escalar se transmite para que tenga la misma forma que el otro argumento.

In [28]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [29]:
x = tf.reshape(x, [3,1])
y = tf.range(1,5)
print(x, "\n")
print(y, "\n")

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



In [30]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Del mismo modo, los ejes con longitud 1 se pueden estirar para que coincidan con los otros argumentos. Ambos argumentos se pueden estirar en el mismo cálculo.

En este caso, una matriz de 3x1 se multiplica por elementos por una matriz de 1x4 para producir una matriz de 3x4. Observe que el 1 inicial es opcional: la forma de y es [4]. En matemáticas esta multiplicación se conoce como producto externo.

### 8.1 tf.broadcast_to

In [31]:
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


### 8.2 tf.convert_to_tensor

La mayoría de las operaciones, como tf.matmul y tf.reshape toman argumentos de la clase tf.tensor. Sin embargo, notará que en el caso anterior, se aceptan objetos de Python con forma de tensores.

La mayoría, pero no todas, las operaciones llaman a tf.convert_to_tensor con argumentos no tensoriales. Existe un registro de conversiones, y la mayoría de las clases de objetos como ndarray , TensorShape , de Python, y tf.variable se convertirán todas automáticamente.

## 9. Tensores irregulares (ragged tensors)

Un tensor con números variables de elementos a lo largo de algún eje se llama "irregular". Utilice tf.ragged.RaggedTensor para datos irregulares. 

Por ejemplo, esto no se puede representar como un tensor regular: 

![tensor_irregular](ragged.png).



   

In [32]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [33]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
     print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


En su lugar, cree un tf.RaggedTensor usando tf.ragged.constant:

In [34]:
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t.shape)

(4, None)


## 10. Tensores de strings

In [35]:
st = tf.constant("Este tensor string")

print(st)

tf.Tensor(b'Este tensor string', shape=(), dtype=string)


In [36]:
st = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "🥳"])
print(st)

tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'\xf0\x9f\xa5\xb3'], shape=(4,), dtype=string)


El prefijo b indica que el tipo (dtype)  tf.string no es unicode.

In [37]:
print(tf.strings.split(st))

<tf.RaggedTensor [[b'Este', b'tensor', b'string'], [b'Cadena', b'2'], [b'Cadena', b'3'], [b'\xf0\x9f\xa5\xb3']]>


In [38]:
st_split = tf.strings.split(st)
for i in st_split:
    print(i)

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)
tf.Tensor([b'Cadena' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Cadena' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'\xf0\x9f\xa5\xb3'], shape=(1,), dtype=string)


In [39]:
### string to number

st = tf.constant("1 10 10.4")

print(tf.strings.to_number(tf.strings.split(st, " ")))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


## 11. Tensores dispersos. SparseTensor

In [40]:
#  tensor disperso
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(sparse_tensor, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
